export { Navbar } from "./Navbar";
export { Hero } from "./Hero";
export { About } from "./About";
export { Programs } from "./Programs";
export { Downloads } from "./Downloads";
export { Dokumentasi } from "./Dokumentasi";
export { Contact } from "./Contact";
export { Footer } from "./Footer";
export { AnimatedSection } from "./AnimatedSection";
